/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Kasir;

/**
 *
 * @author Djapac
 */
public class FrmMain extends javax.swing.JFrame {

    Kasir kasir;
    
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    FrmMain(Kasir kasir) {
        initComponents();
        this.kasir = kasir;
        lblZaposleni.setText(kasir.getIme() + " " + kasir.getPrezime());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblZaposleni = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRacun = new javax.swing.JMenu();
        jmiPregled = new javax.swing.JMenuItem();
        jmiKreiranje = new javax.swing.JMenuItem();
        jmiIzmena = new javax.swing.JMenuItem();
        jmiPlacanje = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Zaposleni: ");

        menuRacun.setText(" Račun");

        jmiPregled.setText("Pregled računa");
        jmiPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPregledActionPerformed(evt);
            }
        });
        menuRacun.add(jmiPregled);

        jmiKreiranje.setText("Kreiranje računa");
        jmiKreiranje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreiranjeActionPerformed(evt);
            }
        });
        menuRacun.add(jmiKreiranje);

        jmiIzmena.setText("Izmena računa");
        jmiIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmenaActionPerformed(evt);
            }
        });
        menuRacun.add(jmiIzmena);

        jmiPlacanje.setText("Plaćanje računa");
        jmiPlacanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPlacanjeActionPerformed(evt);
            }
        });
        menuRacun.add(jmiPlacanje);

        jMenuBar1.add(menuRacun);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(378, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmenaActionPerformed
        // TODO add your handling code here:
        new FrmPregledRacuna(kasir).setVisible(true);
        
    }//GEN-LAST:event_jmiIzmenaActionPerformed

    private void jmiPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPregledActionPerformed
        // TODO add your handling code here:
        new FrmPregledRacuna(kasir).setVisible(true);
    }//GEN-LAST:event_jmiPregledActionPerformed

    private void jmiKreiranjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreiranjeActionPerformed
        // TODO add your handling code here:
        new FrmKreiranjeRacuna(kasir).setVisible(true);
        
    }//GEN-LAST:event_jmiKreiranjeActionPerformed

    private void jmiPlacanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPlacanjeActionPerformed
        // TODO add your handling code here:
        new FrmPregledRacuna(kasir).setVisible(true);
        
    }//GEN-LAST:event_jmiPlacanjeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiIzmena;
    private javax.swing.JMenuItem jmiKreiranje;
    private javax.swing.JMenuItem jmiPlacanje;
    private javax.swing.JMenuItem jmiPregled;
    private javax.swing.JLabel lblZaposleni;
    private javax.swing.JMenu menuRacun;
    // End of variables declaration//GEN-END:variables
}
