/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Kartica;
import domain.Kasir;
import domain.Racun;
import domain.StatusRacuna;
import domain.StavkaRacuna;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logic.Controller;
import model.ModelTabeleStavke;

/**
 *
 * @author Djapac
 */
public class FrmPlatiRacun extends javax.swing.JFrame {

    Racun racun;
    Kasir kasir;
    List<StavkaRacuna> listaStavki;
    Double ukupanIznos;
    FrmUnesiKarticu forma;
    Kartica kartica;
    
    /**
     * Creates new form FrmPlatiRacun
     */
    public FrmPlatiRacun() {
        initComponents();
    }

    FrmPlatiRacun(Racun r) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Plaćanje računa");
        this.racun = r;
        this.kasir = r.getZaposleni();
        kartica =  new Kartica();
        lblZaposleni.setText(kasir.getIme() + " " +kasir.getPrezime());
        txtBrojRacuna.setText(r.getBrojRacuna());
        txtBrojRacuna.setEnabled(false);
        txtUkupanIznos.setEnabled(false);
        listaStavki = vratiStavke();
        ukupanIznos = 0.0;
        
        ModelTabeleStavke mts = new ModelTabeleStavke(listaStavki);
        tblStavke.setModel(mts);
        
        
        
        for(StavkaRacuna sr : listaStavki){
         double c = sr.getCena() * sr.getKolicina();
         ukupanIznos = ukupanIznos + c;
        }
        
        txtUkupanIznos.setText(ukupanIznos + "");
        btnUnesiKarticu.setEnabled(false);
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblZaposleni = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtUkupanIznos = new javax.swing.JTextField();
        radioKes = new javax.swing.JRadioButton();
        radioKartica = new javax.swing.JRadioButton();
        btnPlati = new javax.swing.JButton();
        btnIzadji = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBrojRacuna = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNovcanik = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKusur = new javax.swing.JTextField();
        btnUnesiKarticu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Zaposleni: ");

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        jLabel3.setText("Ukupan iznos plaćanja");

        txtUkupanIznos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        buttonGroup1.add(radioKes);
        radioKes.setText("Keš");
        radioKes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioKesActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioKartica);
        radioKartica.setText("Kartica");
        radioKartica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioKarticaActionPerformed(evt);
            }
        });

        btnPlati.setText("Plati");
        btnPlati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlatiActionPerformed(evt);
            }
        });

        btnIzadji.setText("Izađi");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        jLabel4.setText("Račun broj: ");

        jLabel2.setText("Dat iznos: ");

        jLabel5.setText("Kusur: ");

        btnUnesiKarticu.setText("Unesi karticu");
        btnUnesiKarticu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiKarticuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUkupanIznos)
                                .addComponent(txtNovcanik)
                                .addComponent(txtKusur))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBrojRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioKes, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioKartica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzadji, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(btnUnesiKarticu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrojRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioKes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioKartica, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnPlati, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(btnUnesiKarticu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUkupanIznos, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNovcanik, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKusur, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                    .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    private void btnPlatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlatiActionPerformed
        // TODO add your handling code here:
        
        if(ukupanIznos <= 0){
            JOptionPane.showMessageDialog(this, "Ukupan iznos nije za plaćanje!" ,"Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!radioKartica.isSelected() && !radioKes.isSelected()){
            JOptionPane.showMessageDialog(this, "Niste čekirali način plaćanja!" ,"Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(radioKes.isSelected()){
            try {
                racun.setStatusRacuna(StatusRacuna.PLACEN_KESOM);
                racun.setIzvestaj(listaStavki.toString());
                
                for(StavkaRacuna sr : listaStavki){
                    sr.setStatusRacuna(StatusRacuna.PLACEN_KESOM);
                }
                
                racun.setListaStavki(listaStavki);
                
                
                String novcanikStr = txtNovcanik.getText().trim();
                
                if(!novcanikStr.matches("\\d+")){
                    JOptionPane.showMessageDialog(this, "Iznos koji se daje ne sadrži samo cifre!");
                    return;
                 }

                 int novcanik = Integer.parseInt(novcanikStr);
                 
                 Double kusur = novcanik - ukupanIznos;
                 txtKusur.setText(kusur + " ");
                 
                 
                 
                Controller.getInstance().updateBill(racun);
                JOptionPane.showMessageDialog(this, "Sistem je platio račun!", "Plaćanje računa", JOptionPane.INFORMATION_MESSAGE);
                
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da plati račun kešom" ,"Greška", JOptionPane.ERROR_MESSAGE);
            }
         
            
            
        }
        
        if(radioKartica.isSelected()){
            try {
                racun.setStatusRacuna(StatusRacuna.PLACEN_KARTICOM);
                racun.setIzvestaj(listaStavki.toString());
                txtNovcanik.setEnabled(false);
                txtKusur.setEnabled(false);
                
                
                for(StavkaRacuna sr : listaStavki){
                    sr.setStatusRacuna(StatusRacuna.PLACEN_KARTICOM);
                }
                
                racun.setListaStavki(listaStavki);
                
                
                
                
                
                
                if(kartica.getBrojKartice().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Sistem ne može da plati račun karticom" ,"Greška", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                Controller.getInstance().updateBill(racun);
                JOptionPane.showMessageDialog(this, "Sistem je platio račun!", "Plaćanje računa", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(this, "Sistem ne može da plati račun karticom" ,"Greška", JOptionPane.ERROR_MESSAGE);

            }
            
            
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_btnPlatiActionPerformed

    private void radioKarticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioKarticaActionPerformed
        // TODO add your handling code here:
        txtNovcanik.setEnabled(false);
        txtKusur.setEnabled(false);
        btnUnesiKarticu.setEnabled(true);
        
    }//GEN-LAST:event_radioKarticaActionPerformed

    private void radioKesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioKesActionPerformed
        // TODO add your handling code here:
        txtNovcanik.setEnabled(true);
        txtKusur.setEnabled(true);
        btnUnesiKarticu.setEnabled(false);
    }//GEN-LAST:event_radioKesActionPerformed

    private void btnUnesiKarticuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiKarticuActionPerformed
        // TODO add your handling code here:
        new FrmUnesiKarticu(this, kartica).setVisible(true);
    }//GEN-LAST:event_btnUnesiKarticuActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnPlati;
    private javax.swing.JButton btnUnesiKarticu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblZaposleni;
    private javax.swing.JRadioButton radioKartica;
    private javax.swing.JRadioButton radioKes;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtBrojRacuna;
    private javax.swing.JTextField txtKusur;
    private javax.swing.JTextField txtNovcanik;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private List<StavkaRacuna> vratiStavke() {
        try {
            StavkaRacuna sr = new StavkaRacuna();
            sr.setRacun(racun);
            
            
            List<StavkaRacuna> lista = Controller.getInstance().findBillItems(sr);
            return lista;
           
        } catch (Exception ex) {
            Logger.getLogger(FrmIzmeniStavkuRacuna.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public void setKartica(Kartica k){
        this.kartica = k;
    }
}
